baseURL = 'https://www.nisce.gallery/nisce/public/'
languageCode = 'en-us'
theme = 'hermit-v2'

[languages]
  [languages.en]
    title = 'Nisce'
    [languages.en.params]
      homeSubtitle = "Nisce makes it easy to curate your photos and videos."
    weight = 1

[params.author]
  name = "Yotam Hochman"

[params]
  homeSubtitlePrinter = true
  [[params.socialLinks]]
    name = "appstore"
    url = "https://apps.apple.com/app/nisce/id6739634955"


[menu]

  [[menu.main]]
    name = "Support"
    url = "support/"
    weight = 1

  [[menu.main]]
    name = "Privacy Policy"
    url = "privacy-policy/"
    weight = 2

